export const mockUsers = [
  {
    userId: 1,
    firstName: 'Oli',
    lastName: 'Wiese',
    email: 'oliverwiese@email.de',
  },
  {
    userId: 2,
    firstName: 'Anna',
    lastName: 'Schmidt',
    email: 'annaschmidt@email.de',
  },
  {
    userId: 3,
    firstName: 'Max',
    lastName: 'Mustermann',
    email: 'maxmustermann@email.de',
  },
  {
    userId: 4,
    firstName: 'Lisa',
    lastName: 'Müller',
    email: 'lisamueller@email.de',
  },
  {
    userId: 5,
    firstName: 'David',
    lastName: 'Garcia',
    email: 'davidgarcia@email.de',
  },
  {
    userId: 6,
    firstName: 'Sarah',
    lastName: 'Lee',
    email: 'sarahlee@email.de',
  },
  {
    userId: 7,
    firstName: 'Markus',
    lastName: 'Bauer',
    email: 'markusbauer@email.de',
  },
  {
    userId: 8,
    firstName: 'Julia',
    lastName: 'Wolf',
    email: 'juliawolf@email.de',
  },
  {
    userId: 9,
    firstName: 'Felix',
    lastName: 'Maier',
    email: 'felixmaier@email.de',
  },
  {
    userId: 10,
    firstName: 'Sophie',
    lastName: 'Schulz',
    email: 'sophieschulz@email.de',
  },
  {
    userId: 11,
    firstName: 'Johannes',
    lastName: 'Krause',
    email: 'johanneskrause@email.de',
  },
  {
    userId: 12,
    firstName: 'Mia',
    lastName: 'Weber',
    email: 'miaweber@email.de',
  },
  {
    userId: 13,
    firstName: 'Jonas',
    lastName: 'Becker',
    email: 'jonasbecker@email.de',
  },
  {
    userId: 14,
    firstName: 'Paul',
    lastName: 'Hoffmann',
    email: 'paulhoffmann@email.de',
  },
  {
    userId: 15,
    firstName: 'Marie',
    lastName: 'Schwarz',
    email: 'marieschwarz@email.de',
  },
];

export const mockEvents = [
  {
    eventId: 1,
    creatorId: 1,
    title: 'Raid Night',
    dateTime: '2023-03-21T19:30',
    description: 'Fun gaming night with the group.',
    attendees: [1, 2, 5, 7, 8],
  },
  {
    eventId: 2,
    creatorId: 3,
    title: 'Movie Night',
    dateTime: '2023-04-10T20:00',
    description: 'Watching latest releases in cinema.',
    attendees: [2, 3],
  },
  {
    eventId: 3,
    creatorId: 5,
    title: 'Hiking Trip',
    dateTime: '2023-05-15T08:00',
    description: 'Exploring scenic mountain trails.',
    attendees: [3, 4],
  },
  {
    eventId: 4,
    creatorId: 9,
    title: 'Board Game Night',
    dateTime: '2023-06-02T18:00',
    description: 'Playing classic and modern board games.',
    attendees: [1, 3, 5],
  },
];
